### ISSUE TITLE
There was a problem with the eval: NameError: name 'device' is not defined

### ISSUE THREAD

**Issue by vivibyl** [WendongZh/SPL#10]
![image](https://user-images.githubusercontent.com/96947061/148717631-c4d1351f-21b8-4585-a53a-dbc2a737d90d.png)
Looking forward to your reply！Thanks!

**Comment by WendongZh** [comment]
Thanks for your interest!

It seems that you try to evaluate our model with CPU only. The reason for this error lies in that the current code only supports evaluation with GPUs. Sorry for that.

So the solution is, if you have no GPU for test, you can simply remove all the "device" and ".cuda()" in eval_final.py file, and remove line 186 to line 193 in eval_final.py file. I think it may works. In this case, you should use command as follows:
```bash
python eval_final.py --bs 50 --cpu --dataset paris \
        --img_flist your/test/image/flist/ --mask_flist your/flist/of/masks --mask_index your/npy/file/to/form/img-mask/pairs \
        --model checkpoints/x_launcherRN_bs_4_epoch_best.pt --save --save_path ./test_results
```
 If you have at least on GPU, you can directly use our provided command:
```bash
CUDA_VISIBLE_DEVICES=0 python eval_final.py --bs 50 --gpus 1 --dataset paris \
        --img_flist your/test/image/flist/ --mask_flist your/flist/of/masks --mask_index your/npy/file/to/form/img-mask/pairs \
        --model checkpoints/x_launcherRN_bs_4_epoch_best.pt --save --save_path ./test_results
```
This command will use the GPU for evaluation.

Good luck for you.
