### ISSUE TITLE
Visualization of Learned Semantic Priors

### ISSUE THREAD

**Issue by Pei233** [WendongZh/SPL#11]
Hi, I want to know how to obtain the visualization map of Learned Semantic Priors, just like Fig.5 of your IJCAI paper showed.

I noticed that you use the K-means algorithm on the learned semantic priors and use different colors to represent different clusters. But I am interested in the specific steps that how to cluster.

Could you provide some codes or materials for me?

Thank you very much.

**Comment by WendongZh** [comment]
Thanks for your interests!

You can refer to this [issue](https://github.com/WendongZh/SPL/issues/7). 

Good luck for you.

**Comment by WendongZh** [comment]
I have provided the function ``'Kmeans_map(x)' to draw the visualization results in the main.py of [SPN](https://github.com/WendongZh/SPN/tree/main/SPN_determine).

Thanks for your interests.
