### ISSUE TITLE
About load the pretrained TR_resNet?

### ISSUE THREAD

**Issue by crazygirl1992** [WendongZh/SPL#4]
Hi,i run your code and i find a problem, It is what to choice the TR_ReNet? There are different models,and when i choice the 448*448 on VOC,the errors happen.
![图片](https://user-images.githubusercontent.com/26948839/133233027-34025e8e-7f57-4f74-96b6-720a94265876.png)

**Comment by WendongZh** [comment]
Thanks for your interest!

As we mentioned in the ReadMe, we use the TResNet_L architecture pretrained on OpenImage dataset. 

If you want to change the pretrained model, you can select the same architecture (TResNet_L). If you want to use other architecture such as TResNet_XL on VOC, additional modifications should be considered such as feature map channels in our distill head and (maybe) other particular layers in TResNet_XL with the same output size.
